version: '3'

services:
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/dumps/Dump20211116.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    container_name: mysql

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.3
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
#    environment:
#      - RABBITMQ_DEFAULT_USER=admin
#      - RABBITMQ_DEFAULT_PASS=123456

  temporary_storage:
    build: ./temporary_storage
    volumes:
      - ./temporary_storage/output:/opt/temporary_storage/output
      - ./temporary_storage/input:/opt/temporary_storage/input
    ports:
      - "9003:9003"
    restart: always
    container_name: temporary_storage

  gateway:
    build: ./gateway
#    volumes:
#      - ./api/m1_yolo/output:/opt/object_detection_video/output
#      - ./api/m1_yolo/videos:/opt/object_detection_video/videos
    ports:
      - "9005:9005"
    restart: always
#    command: "python3 wait.py"
    container_name: gateway

  m1_yolo:
    build: ./api/m1_yolo
    volumes:
      - ./api/m1_yolo/output:/opt/object_detection_video/output
      - ./api/m1_yolo/videos:/opt/object_detection_video/videos
    restart: always
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    container_name: yolo
